[features]
seeds = false
[programs.localnet]
deposit_game = "5YZgcGBxfWRDmFX9oiXVQwTZH4QMVG7h6T11kkujbXC4"
[programs.devnet]
deposit_game = "5YZgcGBxfWRDmFX9oiXVQwTZH4QMVG7h6T11kkujbXC4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
